// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsMDwOQ5ESGgyfasCYkhkQt-u00XNohaY',
    appId: '1:86553237919:web:b47f8c9ef4c2587ad145aa',
    messagingSenderId: '86553237919',
    projectId: 'safehouse-7fa8a',
    authDomain: 'safehouse-7fa8a.firebaseapp.com',
    storageBucket: 'safehouse-7fa8a.firebasestorage.app',
    measurementId: 'G-GLV1CVMC5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdb4lVUD3mpetUTunEvdgwERRqWGfXlS8',
    appId: '1:86553237919:android:8cba09373ce7b3a9d145aa',
    messagingSenderId: '86553237919',
    projectId: 'safehouse-7fa8a',
    storageBucket: 'safehouse-7fa8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADb8byROaWr5YILRlrfal2RvujnIL3sTc',
    appId: '1:86553237919:ios:4b84040405168b39d145aa',
    messagingSenderId: '86553237919',
    projectId: 'safehouse-7fa8a',
    storageBucket: 'safehouse-7fa8a.firebasestorage.app',
    iosBundleId: 'com.victorartonomy.com.safeHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADb8byROaWr5YILRlrfal2RvujnIL3sTc',
    appId: '1:86553237919:ios:4b84040405168b39d145aa',
    messagingSenderId: '86553237919',
    projectId: 'safehouse-7fa8a',
    storageBucket: 'safehouse-7fa8a.firebasestorage.app',
    iosBundleId: 'com.victorartonomy.com.safeHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsMDwOQ5ESGgyfasCYkhkQt-u00XNohaY',
    appId: '1:86553237919:web:5c1bc83ab6852ea9d145aa',
    messagingSenderId: '86553237919',
    projectId: 'safehouse-7fa8a',
    authDomain: 'safehouse-7fa8a.firebaseapp.com',
    storageBucket: 'safehouse-7fa8a.firebasestorage.app',
    measurementId: 'G-Z0XVDEXEV4',
  );
}
